[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "next dev"
  port = 3000
  targetPort = 3000
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Skip post-processing (use only if you're having post-processing issues)
#[build.processing]
#  skip_processing = true
